// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMruwiN6caBNR6BE6cBuyoV749_D7e0L4',
    appId: '1:345482176984:web:39837f49377266ac4e2aad',
    messagingSenderId: '345482176984',
    projectId: 'altunbasak-f1c45',
    authDomain: 'altunbasak-f1c45.firebaseapp.com',
    storageBucket: 'altunbasak-f1c45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8YjtZKzP1W3NsULZnBFW9ZPqEIx7psks',
    appId: '1:345482176984:android:9c385998d2c5cf994e2aad',
    messagingSenderId: '345482176984',
    projectId: 'altunbasak-f1c45',
    storageBucket: 'altunbasak-f1c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4AwVddTF828LLPUOcoQcclwsJhOa5Qv0',
    appId: '1:345482176984:ios:583027fbb39e206a4e2aad',
    messagingSenderId: '345482176984',
    projectId: 'altunbasak-f1c45',
    storageBucket: 'altunbasak-f1c45.appspot.com',
    iosClientId: '345482176984-0s4ntjomb0e4tc4u0uaf3ivqagt9npua.apps.googleusercontent.com',
    iosBundleId: 'com.example.altunbasakadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4AwVddTF828LLPUOcoQcclwsJhOa5Qv0',
    appId: '1:345482176984:ios:583027fbb39e206a4e2aad',
    messagingSenderId: '345482176984',
    projectId: 'altunbasak-f1c45',
    storageBucket: 'altunbasak-f1c45.appspot.com',
    iosClientId: '345482176984-0s4ntjomb0e4tc4u0uaf3ivqagt9npua.apps.googleusercontent.com',
    iosBundleId: 'com.example.altunbasakadmin',
  );
}
